# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "2.7"

env:
    - DJANGO="Django==1.8"
    - DJANGO="Django==1.9"

# command to install dependencies, e.g. pip install -r requirements.txt
install:
 - pip install $DJANGO
 - pip install wheel==0.24.0
 - pip install -r requirements-test.txt

# command to run tests using coverage, e.g. python setup.py test
script: coverage run --source usersettings runtests.py

# report coverage to coveralls.io
after_success: coveralls
